spec:
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  - namespace: apps
    server: https://kubernetes.default.svc
