apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  description: Applications Project
  sourceRepos:
  - https://github.com/hideto0710/gitops-sample.git
  destinations:
  {{- range .Values.spec.destinations }}
  - namespace: {{ .namespace }}
    server: {{ .server }}
  {{- end }}
