apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  description: Applications Project
  sourceRepos:
  - https://github.com/hideto0710/gitops-sample.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
