apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops
spec:
  description: Operations Project
  sourceRepos:
  - https://github.com/hideto0710/gitops-sample.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
