apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  destination:
    namespace: app
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: nginx-app
    repoURL: https://github.com/hideto0710/gitops-sample.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
