apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: ops
  source:
    path: sealed-secrets
    repoURL: https://github.com/hideto0710/gitops-sample.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
